executable = skimProduction/condor/job.sh
arguments  = $(ARGS)

output = skimProduction/condor/logs/job_$(ClusterId)_$(ProcId).out
error  = skimProduction/condor/logs/job_$(ClusterId)_$(ProcId).err
log    = skimProduction/condor/logs/job_$(ClusterId)_$(ProcId).log

request_cpus   = 1
request_memory = 4 GB

+JobFlavour = "tomorrow"

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

# 🔥 SOLO TARBALL
transfer_input_files = framework.tar.gz

# (opzionale ma consigliato)
getenv = True

queue ARGS from (