era: Run3_2024
luminosity: 109948.18  # pb-1, https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun3Analysis#DATA_AN2 command brilcalc lumi -b "STABLE BEAMS" --normtag /cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags/normtag_PHYSICS.json -u /pb -i Cert_Collisions2024_378981_386951_Golden.json

final_skim_folder:

crossSectionsFile: config/crossSections13p6TeV.yaml
samplesFile: config/samples_2024.yaml
lumiFile: /afs/cern.ch/user/v/vdamante/H_mumu/Corrections/data/golden_json/Cert_Collisions2024_378981_386951_Golden.json
triggerFile: /afs/cern.ch/work/v/vdamante/Hmm_newSkim/config/triggers_2024.yaml
sel_file: /afs/cern.ch/work/v/vdamante/Hmm_newSkim/config/selections_2024.yaml

nano_version: v15
ignore_missing_nanoAOD_files:
  data: False
  signals: True
  backgrounds: True


MET_flags:  # https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2#Run_3_2024_data_and_MC_Recommend
  - Flag_goodVertices
  - Flag_globalSuperTightHalo2016Filter
  - Flag_EcalDeadCellTriggerPrimitiveFilter
  - Flag_BadPFMuonFilter
  - Flag_BadPFMuonDzFilter
  - Flag_hfNoisyHitsFilter
  - Flag_eeBadScFilter
  - Flag_ecalBadCalibFilter

only_default: True
want_variations: True
apply_trg_filter: True

bTagAlgo: UParTAK4
# corrections:
#   btag:
#     tagger: UParTAK4
#     jetCollection: Jet
#   mu:
#     stage: HistTuple # AnaTuple
#     columns:
#       pfRelIso04_all: pfRelIso04_all
#       tightId: tightId
#       tkRelIso: tkRelIso
#       highPtId: highPtId
#       mediumId: mediumId
#       looseId: looseId
#       p4: p4 # it is the final ScaRe corrected p4, either BSC or nano according to chi2 --> has to be modified with the non-corrected pT
#     lowPt: True
#     midPt: True
#     hiPt: False
#   trigger:
#     stages: HistTuple # AnaTuple
#     mode: SF
#     extraFormat:
#       pt: "bsConstrainedPt"
#   muScaRe:
#     stages: [ AnaTuple, AnalysisCache, HistTuple ]
#     scare_enabled:
#       AnaTuple: true
#       AnalysisCache: false
#       HistTuple: false
#     fsr_enabled:
#       AnaTuple: false
#       AnalysisCache: true
#       HistTuple: true
#     mu_pt_for_ScaReApplication: "bsConstrainedPt"
#   lumi: { stage: AnaTuple }
#   xs: { stage: AnaTuple }
#   gen: { stage: AnaTuple }
#   pu:
#     stages: [ AnaTuple, AnaTupleMerge ]
#     enabled:
#       AnaTuple: true
#       AnaTupleMerge: false
#   base: { stage: AnaTupleMerge }
#   JEC: { stage: AnaTuple }
#   JER:
#     stage: AnaTuple
#     apply_jet_horns_fix: true
