default_suffix: _ScaRe_FSR
additional_suffix: ["_noCorr", "_ScaRe", "_scale", "_noCorr_FSR", "_scale_FSR"]
varied_suffix: ["_scale_FSR_up", "_scale_FSR_down", "_resol_FSR_up", "_resol_FSR_down"]
varied_additional_suff: ["_scale_up", "_scale_down", "_resol_up", "_resol_down"]

masses_regions:
    Z_sideband: "m_mumu{suff} > 70 && m_mumu{suff} < 110"
    Signal_Fit: "m_mumu{suff} > 115 && m_mumu{suff} < 135"
    H_sideband: "((m_mumu{suff} > 110 && m_mumu{suff} < 115) || (m_mumu{suff} > 135 && m_mumu{suff} < 150))"
    Signal_ext: "m_mumu{suff} > 110 && m_mumu{suff} < 150"
    mass_inclusive: "m_mumu{suff} > 60 && m_mumu{suff} < 150"


muon_presel_pt_cut: 15.0
dimuon_m_cut: 50.0

muons_selection:
  muon_pre_sel_check: "mu1_pt{suff} > 15 && abs(mu1_eta) < 2.4 && mu2_pt{suff} > 15 && abs(mu2_eta) < 2.4"
  OS: mu1_charge * mu2_charge < 0
  OS_presel: "muon_pre_sel_check && OS"
  trigger: "( Event_HasTriggerMatching_singleMu && HLT_IsoMu24 && ( ( mu1_pt{suff} > 26 && mu1_HasTriggerMatching_singleMu{suff}) || (mu2_pt{suff} > 26 && mu2_HasTriggerMatching_singleMu{suff}) ) ) " # official
  mu1_pt_l30: "mu1_pt{suff} < 30"
  mu2_pt_l30: "mu2_pt{suff} < 30"
  mu1_pt_g20: "mu1_pt{suff} > 20"
  mu2_pt_g20: "mu2_pt{suff} > 20"
  mu_pt_sel: "mu1_pt_g20 && mu2_pt_g20"
  mu1_ML: "mu1_pfIsoId >= 2 && mu1_mediumId"
  mu1_LL: "mu1_pfIsoId >= 2 && mu1_looseId"
  mu1_TT: "mu1_pfIsoId >= 4 && mu1_tightId"
  mu2_ML: "mu2_pfIsoId >= 2 && mu2_mediumId"
  mu2_LL: "mu2_pfIsoId >= 2 && mu2_looseId"
  mu2_TT: "mu2_pfIsoId >= 4 && mu2_tightId"
  bothMuons_ML: "mu1_ML && mu2_ML"
  bothMuons_LL: "mu1_LL && mu2_LL"
  chi2_sel: "mu1_bsConstrainedChi2 < 30 && mu2_bsConstrainedChi2 < 30"
  pt_lessthan30_and_TT: "(((mu1_pt_l30 && mu1_TT) || !(mu1_pt_l30)) && ((mu2_pt_l30 && mu2_TT) || !(mu2_pt_l30)))"

jets_selection:
  jets_horn_veto:
  jets_cleanFromMu_sel: "JetTagSel"


categories:
  base_sel: "mu_pt_sel && trigger_sel && OS_sel && jets_cleanFromMu_sel"
  baseline: "base_sel && mu1_ML && mu2_ML"
  # baseline_thirdLepVeto: "baseline && vetoed_muons==0"
  baseline_chi2: "baseline && chi2_sel"
  baseline_lowPtTT: "(baseline) && (pt_lessthan30_and_TT)"

  # baseline_thirdLepVeto_chi2: "baseline && chi2_sel && vetoed_muons==0"
  # baseline_thirdLepVeto_lowPtTT: "baseline && (pt_lessthan30_and_TT) && vetoed_muons==0"
  baseline_chi2_lowPtTT: "baseline && (pt_lessthan30_and_TT) && chi2_sel"
  # baseline_thirdLepVeto_lowPtTT_chi2: "baseline && (pt_lessthan30_and_TT) && chi2_sel && vetoed_muons==0"

  # j1_outside_horn: "(abs(j1_eta) < 2.5 || abs(j1_eta) > 3 || j1_pt > 50)"
  # j2_outside_horn: "(abs(j2_eta) < 2.5 || abs(j2_eta) > 3 || j2_pt > 50)"
  VBF_def: "HasVBF && j1_pt >= 35 && j2_pt >= 25"

  VBF: "baseline && VBF_def"
  ggF: "baseline && !(VBF_def)"
  # # VBF_thirdLepVeto: "baseline_thirdLepVeto && VBF_def"
  # # ggF_thirdLepVeto: "baseline_thirdLepVeto && !(VBF_def)"
  VBF_chi2: "baseline_chi2 && VBF_def"
  ggF_chi2: "baseline_chi2 && !(VBF_def)"
  VBF_lowPtTT: "baseline_lowPtTT && VBF_def"
  ggF_lowPtTT: "baseline_lowPtTT && !(VBF_def)"
  # # VBF_thirdLepVeto_chi2: "baseline_thirdLepVeto_chi2 && VBF_def"
  # # ggF_thirdLepVeto_chi2: "baseline_thirdLepVeto_chi2 && !(VBF_def)"
  VBF_chi2_lowPtTT: "baseline_chi2_lowPtTT && VBF_def"
  ggF_chi2_lowPtTT: "baseline_chi2_lowPtTT && !(VBF_def)"
  # # VBF_thirdLepVeto_lowPtTT: "baseline_thirdLepVeto_lowPtTT && VBF_def"
  # # ggF_thirdLepVeto_lowPtTT: "baseline_thirdLepVeto_lowPtTT && !(VBF_def)"
  # # VBF_thirdLepVeto_lowPtTT_chi2: "baseline_thirdLepVeto_lowPtTT_chi2 && VBF_def"
  # # ggF_thirdLepVeto_lowPtTT_chi2: "baseline_thirdLepVeto_lowPtTT_chi2 && !(VBF_def)"

  # mu1_prompt: "(mu1_genPartIdx >= 0 && mu1_gen_kind == 2)"
  # mu2_prompt: "(mu2_genPartIdx >= 0 && mu2_gen_kind == 2)"
  # mu1_from_tau: "(mu1_genPartIdx >= 0 && mu1_gen_kind == 4)"
  # mu2_from_tau: "(mu2_genPartIdx >= 0 && mu2_gen_kind == 4)"
  # both_muons_true_prompt: "mu1_prompt && mu2_prompt"
  # at_least_one_muon_from_tau: "!(both_muons_true_prompt) && (mu1_from_tau || mu2_from_tau)"
  # any_muon_not_true: "!(both_muons_true_prompt) && !(at_least_one_muon_from_tau)"
