features:
  - era_code
  - mu1_eta
  - mu1_pt
  - mu2_eta
  - mu2_pt
  - dR_mumu
  - eta_mumu
  - cosTheta_CS
  - phi_mumu
  - m_mumu
  - pt_mumu
  - y_mumu
  - phi_CS
  - R_pt
  - minDeltaEtaSigned
  - minDeltaPhi
  - Zeppenfeld_Var
  - pt_centrality
  - vbfjet1_eta
  - vbfjet1_pt
  - vbfjet1_y
  - vbfjet1_btagPNetQvG
  - vbfjet2_eta
  - vbfjet2_pt
  - vbfjet2_y
  - vbfjet2_btagPNetQvG
  - m_jj
  - delta_eta_jj
  - pt_vbfj1j2
  - N_SelectedJets
  - SoftJetCleanedActivity_N
  - SoftJetCleanedActivity_ptSum