import os
import sys
import argparse
import fnmatch
import zlib
from pathlib import Path
import ROOT
import utilities

# Ensure local packages can be imported when running this script directly.
ROOT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT_DIR))

headers_dir = os.path.dirname(os.path.abspath(__file__))
header_path = os.path.join(headers_dir, "AnalysisTools.h")
ROOT.gInterpreter.Declare(f'#include "{header_path}"')


def _parse_args():
    parser = argparse.ArgumentParser(description="Run the Hmumu skim.")
    parser.add_argument(
        "--config-file",
        required=True,
        type=str,
        help="Path to the main skim configuration YAML.",
    )
    parser.add_argument(
        "--input-file",
        required=True,
        type=str,
        help="Input ROOT file or XRootD URI.",
    )
    parser.add_argument(
        "--dataset-name",
        required=True,
        type=str,
        help="Dataset key in the samples YAML.",
    )
    parser.add_argument(
        "--output-file",
        required=True,
        type=str,
        help='Output ROOT file.',
    )
    return parser.parse_args()


def _get_new_muon_cols(df):
    """ Dynamically updates the list of new columns to be saved in the output file """
    available_columns = {str(column) for column in df.GetColumnNames()}
    muon_patterns = [
        "mu1_idx*", "mu2_idx*",
        "mu1_pt*",  "mu2_pt*",
        "mu1_eta*", "mu2_eta*",
        "mu1_phi*", "mu2_phi*",
        "mu1_mass*", "mu2_mass*",
        "mu1_charge*", "mu2_charge*",
        "mu1_bsConstrainedChi2*", "mu2_bsConstrainedChi2*",
        "mu1_dxy*", "mu2_dxy*",
        "mu1_dz*",  "mu2_dz*",
        "mu1_pfIsoId*", "mu2_pfIsoId*",
        "mu1_mediumId*", "mu2_mediumId*",
        "m_mumu*", "pt_mumu*", "eta_mumu*", "phi_mumu*", "y_mumu*", "dR_mumu*",
    ]

    muon_cols = []
    # Match wildcard patterns against actual dataframe columns generated by ProcessMuons
    for pattern in muon_patterns:
        matched = fnmatch.filter(available_columns, pattern)
        muon_cols.extend(matched)
    return muon_cols


# --- Main Logic Execution ---
args = _parse_args()
config_file = args.config_file
input_file = args.input_file
dataset_name = args.dataset_name
output_file = args.output_file

config = utilities.get_config(config_file)
cols_to_save = []
period = config["era"]
lumi = config["luminosity"]
nano_version = config.get("nano_version", "v15")

dataset_cfg = utilities.get_config(config["samplesFile"])[dataset_name]
xs_cfg = utilities.get_config(config["crossSectionsFile"])
is_data = dataset_cfg.get("is_data", False)
is_signal = dataset_cfg.get("is_signal", False)

trigger_config = utilities.get_config(config.get("triggerFile"))

root_file = ROOT.TFile.Open(input_file)
tree = root_file.Get("Events")
df = ROOT.RDataFrame(tree)


# 1. Base weights, triggers and MET flags corrections
from corrections.general import define_base_weights, apply_corrections
if "MET_flags" in config:
    from analysis.other import applyMETFlags
    df = applyMETFlags(df, config, is_data)

df = df.Define("period", f"static_cast<int>(Period::{period})")
is_data_str = "true" if is_data else "false"
df = df.Define(f"is_data", is_data_str)
is_data_int = "1" if is_data else "0"
df = df.Define(f"is_data_int", is_data_int)

is_signal_str = "true" if is_signal else "false"
df = df.Define(f"is_signal", is_signal_str)

# Create unique Event ID
dataset_name_crc = zlib.crc32(dataset_name.encode()) & 0xFFFF
input_file_crc = zlib.crc32(input_file.encode()) & 0xFFFF
df = df.Define(
    fullEventIdColumn := "FullEventId",
    f"eventId::encodeFullEventId({dataset_name_crc}, {input_file_crc}, rdfentry_)",
)

# Populate standard columns to store
default_col_to_store = utilities.GetObservablesCols("default", is_data, nano_version)
cols_to_save.extend(default_col_to_store)

df, base_weights_to_store = define_base_weights(df, config, dataset_name, xs_cfg)
cols_to_save.extend(base_weights_to_store)

df, pu_branches = apply_corrections(df, config, dataset_cfg, dataset_name)
if pu_branches:
    cols_to_save.extend(pu_branches)


# 2. Refactored Muon & Dimuon Selection Block
from analysis.muons import ProcessMuons, ApplyElectronVeto

muon_cols_initial = utilities.GetObservablesCols("Muon", is_data, nano_version)

only_fsr = config.get("only_fsr", True)
want_variations = config.get("want_variations", False)
pt_cut = config.get("muon_pt_min", 15.0)
m_cut = config.get("dimuon_mass_min", 50.0)

# Run simplified framework processing chain
df,new_muon_cols = ProcessMuons(
    df=df,
    is_data=is_data,
    muon_columns=muon_cols_initial,
    only_fsr=only_fsr,
    want_variations=want_variations,
    pt_min=pt_cut,
    mass_cut=m_cut
)
df = ApplyElectronVeto(df)
cols_to_save.extend(new_muon_cols)


from corrections.jetVetoMap import ApplyJetVetoMap
df,jet_veto_map_cols = ApplyJetVetoMap(df, config, apply_filter=False, defineElectronCleaning=False, isV12=nano_version=="v12")
cols_to_save.extend(jet_veto_map_cols)


jet_cols = utilities.GetObservablesCols(
    "Jet",
    is_data,
    nano_version,
)
cols_to_save.extend(jet_cols)

LHE_weight_cols = utilities.GetObservablesCols(
    "LHEWeight", is_data, nano_version
)
cols_to_save.extend(LHE_weight_cols)
SoftActivityJet_cols = utilities.GetObservablesCols(
    "SoftActivityJet", is_data, nano_version
)
cols_to_save.extend(SoftActivityJet_cols)
FsrPhoton_cols = utilities.GetObservablesCols(
    "FsrPhoton", is_data, nano_version
)
cols_to_save.extend(FsrPhoton_cols)
cols_to_save= list(set(cols_to_save))
print("Columns configured to be saved:")
print(cols_to_save)

df.Snapshot("Events", output_file, utilities.ListToVector(cols_to_save))